"""Generate the CLI and REST reference pages from the code, so they cannot drift.

    python -m tools.docs.gen_reference           # (re)write docs/guide/reference/*.md
    python -m tools.docs.gen_reference --check   # exit 1 if the committed pages are stale

`tests/docs/test_reference_docs.py` runs the check, so a new command or route that is not
reflected in the docs fails the suite — the same idea as the doc-lint gate, applied to the
user-facing reference.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any

import click
import typer

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "docs" / "guide" / "reference"
_HEADER = "<!-- GENERATED by `python -m tools.docs.gen_reference` — do not edit by hand. -->\n\n"
_HTTP_METHODS = ("get", "post", "put", "patch", "delete")


def _first_paragraph(text: str | None) -> str:
    if not text:
        return ""
    para = text.strip().split("\n\n", 1)[0]
    return " ".join(line.strip() for line in para.splitlines()).replace("|", "\\|")


def _default(param: click.Parameter) -> str:
    value = param.default
    if value is None or value == () or callable(value) or isinstance(param, click.Argument):
        return ""
    if isinstance(value, bool):
        return "on" if value else "off"
    return f"`{str(value).replace(chr(92), '/')}`" if str(value) != "" else ""


def _param_rows(command: click.Command) -> list[str]:
    rows: list[str] = []
    for param in command.params:
        if param.name == "help":
            continue
        if isinstance(param, click.Argument):
            name = f"`{(param.name or '').upper()}`" + ("" if param.required else " *(optional)*")
        else:
            name = ", ".join(f"`{opt}`" for opt in (*param.opts, *param.secondary_opts))
        help_text = _first_paragraph(getattr(param, "help", "") or "")
        rows.append(f"| {name} | {help_text} | {_default(param)} |")
    return rows


def _walk(command: click.Command, path: list[str], out: list[str]) -> None:
    if isinstance(command, click.Group):
        if len(path) > 1:
            out.append(f"## `{' '.join(path)}`\n\n{_first_paragraph(command.help)}\n")
        for name in command.list_commands(click.Context(command)):
            sub = command.get_command(click.Context(command), name)
            if sub is not None:
                _walk(sub, [*path, name], out)
        return
    out.append(f"### `{' '.join(path)}`\n\n{_first_paragraph(command.help)}\n")
    rows = _param_rows(command)
    if rows:
        out.append("| Argument / option | Meaning | Default |\n|---|---|---|\n" + "\n".join(rows) + "\n")


def render_cli() -> str:
    from src.cli import app  # noqa: PLC0415 — keep Typer/CLI import cost out of module import

    root = typer.main.get_command(app)
    assert isinstance(root, click.Group)
    out = [
        "# CLI reference\n",
        "Every command of the `secbrain` CLI, generated from the code. Global options come "
        "before the command: `secbrain --data-dir ./data <command> …`.\n",
        "## Global options\n",
        "| Argument / option | Meaning | Default |\n|---|---|---|\n" + "\n".join(_param_rows(root)) + "\n",
        "## Top-level commands\n",
    ]
    ctx = click.Context(root)
    groups: list[tuple[str, click.Command]] = []
    for name in root.list_commands(ctx):
        sub = root.get_command(ctx, name)
        if sub is None:
            continue
        if isinstance(sub, click.Group):
            groups.append((name, sub))
        else:
            _walk(sub, ["secbrain", name], out)
    for name, group in groups:
        _walk(group, ["secbrain", name], out)
    return _HEADER + "\n".join(out).rstrip() + "\n"


def render_rest() -> str:
    from src.web.app import create_app  # noqa: PLC0415 — FastAPI is an optional extra

    # create_app() loads `.env` into os.environ; do not leak that into the calling process
    # (a test run that imports this would otherwise see the developer's API keys).
    saved_env = dict(os.environ)
    try:
        spec: dict[str, Any] = create_app().openapi()
    finally:
        os.environ.clear()
        os.environ.update(saved_env)
    groups: dict[str, list[tuple[str, str, str]]] = {}
    for path, operations in sorted(spec["paths"].items()):
        for method, operation in operations.items():
            if method not in _HTTP_METHODS:
                continue
            parts = path.split("/")
            group = parts[3] if path.startswith("/api/v1/") and len(parts) > 3 else "root"
            summary = _first_paragraph(operation.get("description") or operation.get("summary"))
            groups.setdefault(group, []).append((method.upper(), path, summary))
    total = sum(len(ops) for ops in groups.values())
    out = [
        "# REST API reference\n",
        f"{total} operations under `/api/v1`, generated from the FastAPI application's OpenAPI "
        "schema. Start the backend with `secbrain ui` (or `uvicorn src.web.app:create_app "
        "--factory`) and open `/docs` for the interactive Swagger UI with full request and "
        "response schemas.\n",
        "> The API is designed for a **single-tenant, local** deployment: there is no "
        "authentication layer and CORS is off. Do not expose it to the internet.\n",
    ]
    for group in sorted(groups):
        out.append(f"## `{group}`\n")
        out.append("| Method | Path | What it does |\n|---|---|---|")
        out.extend(f"| `{m}` | `{p}` | {s} |" for m, p, s in sorted(groups[group], key=lambda r: (r[1], r[0])))
        out.append("")
    return _HEADER + "\n".join(out).rstrip() + "\n"


PAGES = {"cli.md": render_cli, "rest-api.md": render_rest}


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    check = "--check" in args
    stale: list[str] = []
    for name, render in PAGES.items():
        target = OUT_DIR / name
        content = render()
        if check:
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                stale.append(name)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {target.relative_to(REPO_ROOT)}")
    if stale:
        print("stale reference pages: " + ", ".join(stale)
              + " — run `python -m tools.docs.gen_reference`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
